var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                   xxx          ",
   "                                                                  xx!xx         ",
   "   x                                 o o                          x!!!x     x   ",
   "  x                                                               xx!xx      x  ",
   "  x                                 xxxxx                          xvx       x  ",
   "  x                                   v                                      x  ",
   "  x                                        o o                               x  ",
   "  x                     o                                                    x  ",
   "  x                                      xxxx                             o  x  ",
   "  x          xxxx       o                                                    x  ",
   "  x  @       x  x                                                xxxxx       x  ",
   "  xxxxxxxmmmxx  xxxxxxxxxxxxxxx   xxxxxxx         x       x          xxxxxxxxx  ",
   "        hvvvh                  x                                      x          ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          ",
   "                              x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x          ",
   "                              xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx          ",
   "                                                                                ",
   "                                                                                "],
  ["                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                 o                                                                                   ",
   "                    o                       o                   o o o o o o                                          ",
   "      xxxxx                   xxxx                             o o o o o o o                                         ",
   "      v   v   x     xxx       v  v        xxxxx        xxxxxxxxxxxxxxxxxxxxxx                                        ",
   "       vvv    v     v v        vv         v   v         v v  v v  v v  v v                                           ",
   "                     v                     vvv           v    v    v    v                                            ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                                                                                                     ",
   "                                     o                             ooooooooo                  o                      ",
   "       o o                                           o                                                xxxxxxxxxxxxxx ",
   "      xxxxx                                                      xxxxxxxxxxxxx                        xxxxxxxxxxxxxx ",
   "                            oo                              oo   xxxxxxxxxxxxx    o                               xx ",
   "        @                                                        xxxxxxxxxxxxx                     o  o   o       xx ",
   "xxxxxxxxxxxxxxxxxx       xxxxxxxx                        xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                       xx ",
   "xxxxxxxxxxxxxxxxxx       xxxxxxxx        xxxxxxxxx       xxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxx      xxxxxxxxxxxxxtxxxxx ",
   "xxxxxxxxxxxxxxxxxx       xxxxxxxx           xxx          xxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxx ",
   "xxxxxxxxxxxxxxxxxx!!!!!!!xxxxxxxx!!!!!!!!!!!xxx!!!!!!!!!!xxxxxxxx!!!!!!!!!!!!!xxxxxxxxxxxxx!!!!!!xxxxxxxxxxxxxxxxxxx "],
  ["xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "h                                                                                                 xx         x",  
   "h                                                                                                 xx         x",
   "h                                                                                                 xx         x",
   "h                                                                                                 xx         x",
   "h                                                                                                 xx         x",
   "h        @           xx=      =xx=     =xx=     =xx=     =xx=    =xx=    =xx=   =xx=             =xx!!!!!!!!!x",
   "xmmxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxvvxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmmmmmxxxxxxxxxxxx",
   "x                                                                                                          vvx",
   "x                                                                                                            x",
   "x                                                                                                            x",
   "x                                                              x                                             x",
   "x                                                                                              xxxxx         x",
   "x            xxxxxxx    xxxxxxxxxx   xxxxxx  x   xxxxx                                                       x",
   "x    xxx!!!!!xxxxx!!!!!!!!xxxxxxxv                 vv                 x                                      x",
   "x    xx!!!!!!!!!!!!!!!!!!!xxxxxxx         x                                                                  x",
   "x    xxxxxxxxxxx!!!!!!!!!!xxxx==                        x  xxxxx           x      xxxxx                      x",
   "x           =!!!!!!!!!!!!!xxxx                                                      v                        x",
   "x        xxxx!xxxxxxxxxx!xxxxx==            xxxxx                                        x      xxxxx        x",
   "x        xxx!xxxxxxxxxxx!xxxxx                v                  xxxxx                             vv        x",
   "x      v!!!!vx!!!!!vxxx!!!xxxxx                                                                              x",
   "x                       v!xxxx                                           xxxx            xxx                 x",
   "x                     o  !xxxx==           x         xxxxx                                 xxxxx             x",
   "x                        !xxxx                                   xxxxx                                       x",
   "xxxxxxxxxxxxxxxxxxxxxxxxx!xxxx                                              xxxxxxxx                         x",
   "x!!!!!!!!!!!!!!!!!!!!!!!!!xxxx!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!x",
   "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              "],
  ["                                                                                                              ",

   "                                                                                                              ",
   "                                                                                                              ",
   "           xxxx    xxxx   xxxxxxxxxx    xx      xx      xxxx               xxxx   xxxxx  xxx       xx         ",
   "            xxxx  xxxx   xxxxxxxxxxxx  xxx      xxx     xx                    xx   xxx   xxxxx     xx         ",
   "              xxxxxx     xxx      xxx  xxx      xxx      xx                  xx    xxx   xxvvxx    xx         ",
   "               xxxx      xxx      xxx  xxx      xxx       xx                xx     xxx   xx  vxx   xx         ",
   "                xx       xxx!!!!!!xxx  xxx!!!!!!xxx        xx!!!!!!xx!!!!!!xx      xxx   xx   vxx!!xx         ",
   "                xx       xxx!!!!!!xxx  xxx!!!!!!xxx         xx!!!!xxxx!!!!xx       xxx   xx    vxx!xx         ",
   "                xx       xxxxxxxxxxxx  xxxxxxxxxxxx          xx!!xx  xx!!xx        xxx   xx     vxxxx         ",
   "                xx        xxxxxxxxxx    xxxxxxxxxx            xxxxx  xxxxx        xxxxx  xx!!!!!!!xxx         ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "  x                                                                                                          x",
   "  x                                                                                                          x",
   "  x  @                                                                                                       x",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
   "                                                                                                              ",
   "                                                                                                              "]
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
